# Generated by Django 4.2.7 on 2024-12-04 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_coursereservation_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereservation',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.course'),
        ),
    ]
